### ISSUE TITLE
import_dynamo_table missing in python api

### ISSUE THREAD

**Issue by azazellochg** [rkms86/SUSAN#1]
Hi,

I'm trying to follow the tutorial with Python API. I could not find prj_001.ptclsraw anywhere and wanted to convert picked_bin2.tbl, but then I couldn't find the python function to do this. In matlab api I can see import_dynamo_table. I dont have matlab installed. Can I get around this?

**Comment by rsanchezloayza** [comment]
Hi,
I added import/export methods to the Particles class, and updated the python initial example using them.
Be aware that for the tutorial sometimes I used multiple GPUs, modify that part according to your setup.
Let me know if this solves the issue.
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Hi Ricardo, that's a very quick solution, I'll try and let you know! Thanks!
Grigory.

**Comment by azazellochg** [comment]
Hi again, I can succesfully import picked_b8.tbl, however it fails on [this file](https://github.com/KudryashevLab/SUSAN/blob/main/%2BSUSAN/tutorial/susan_projects/picked_bin2.tbl):

`ValueError: could not convert string to float: '0+1.7075e-06i'`

 One column in that tbl sometimes has complex values. I'm not sure if that's a corrupted table or complex numbers are expected in Dynamo.

**Comment by rsanchezloayza** [comment]
Hi Grigory,
I am not so sure if complex values are allowed on a Dynamo table, but the dynamotable package from teamtomo can read it properly. I added an example using it to the python tutorial.
But, I cannot process the picked_b2.tbl table on that repo. I will try to contact the Kudryashev lab about it.
Does the current python tutorial on this repo works?
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Hi, originally I started with the matlab tutorial file workflow_basicStA.m in their repo, but then found you've already got a python tutorial. Considering that the differences with that fork are only tutorial files and things don't work with their files, I'll switch to your repo completely and try to finish your tutorial. Thanks for your help.
