### ISSUE TITLE
python tutorial questions

### ISSUE THREAD

**Issue by azazellochg** [rkms86/SUSAN#2]
I though I'd make a separate issue for my questions.

1) why duplicating particle set for MRA is necessary? because you want to preserve original particle stack? but the project does output particles for each iteration.
2) in the tutorial in the very first project the prj_001_mra.ptclsraw is bin8, while everything else is bin4. It does run, so the binning does not have to match between particles and ref/masks?
3) initial reconstruction is not used in the project, I guess it's calculated only for demonstration?
4) I found that my tomo_size didnt match binned stacks size so I had to replace 3710//2 by math.ceil(3710/2)

**Comment by rsanchezloayza** [comment]
Hi,
1. It was not necessary to keep a copy of it. Overwriting the file would have been enough (I guess you mean having prj_001.ptclsraw and prj_001_mra.ptclsraw).
2. the PTCLSRAW files are binning independent, meaning that the location and shifts are stored in angstroms instead of pixels (and the location is from the center of the tomograms). That way, it is easier to change the binning of the projects: you would need the appropriate ref/masks for the binning level, and the TOMOSTXT file pointing to the corresponding stacks.
3. It was calculated to validate the location of the particles.
4. I will fix it in the next commit.
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Thanks, Ricardo. 
Another thing with MPI. If I put for the manager
```
mngr.mpi.cmd = "mpirun -n %d"
mngr.mpi.arg = 5
```

it fails with:
```
File "/public/EM/Scipion/scipion-dev/software/em/susan-1.0/susan/project.py", line 186, in _exec_alignment
self.aligner.mpi_params.cmd = self.mpi.cmd
AttributeError: 'Aligner' object has no attribute 'mpi_params'
```

I think it should be self.aligner.mpi.cmd instead

**Comment by rsanchezloayza** [comment]
Hi,
I made the modifications, I do not have a cluster to test the MPI functionalities at the moment.
Let me know if everything went well when processing on multiple nodes.
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Submitting with 4 gpus, 4 threads and 5 mpis to a single node via slurm:
- I can see susan_aligner_mpi using 5 MPIs, each using 4 CPU cores 
- I can also see via nvidia-smi 5 processes per each GPU
- I made a [patch.txt](https://github.com/rkms86/SUSAN/files/9262618/patch.txt) for the main branch with minor corrections to make it run

I haven't compared the run speed, but the program itself runs to completion

**Comment by rsanchezloayza** [comment]
Hi Grigory,
Thanks for the patch. I updated the code with it. Also thanks for testing SUSAN.
A few notes about SUSAN architecture. As you may have seen, SUSAN does not crop any particles into hard-disk, it loads (in a double buffer) the aligned stacks and crops the particles (substacks) on-the-fly and then uploads them to the GPU (using a double buffer too, such that the processing and reading is concurrent). So, I used a PThread per requested GPU (actually two for the concurrency) and all of them access to the same memory buffer. In that regard, only one instance of any SUSAN program should be executed per physical node. If you want to use more threads per GPU, you can set the _threads_per_gpu_ property (defaults to 1). MPI is used only to distribute and gather the results between nodes. If I have to use 1 node, I disable the MPI functionality and use the GPUs according to the available nodes. 
I will try to validate SUSAN using multiple nodes, but the cluster I have access to is quite busy. Let's see.
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Hi Ricardo, thank you for the explanation. I will try to run it on two nodes (mpi=3 I guess) and report here.

**Comment by rsanchezloayza** [comment]
Hi Grigory,
mpi 3 would mean 3 nodes. In my implementation all the MPI nodes process data.
Here I show you an example of how I use SUSAN on a cluster with SLURM (2 nodes, 4 GPUs each):
- susan_job_prj001.sh (1 task/node, 10 cpu/task: 2 threads x GPU + Main thread + Stack reader):
```
#!/bin/bash
#SBATCH -p gpu
#SBATCH --job-name=SSAprj1
#SBATCH -N 2
#SBATCH --cpus-per-task=10
#SBATCH -o log.out
#SBATCH -e log.err
#SBATCH --open-mode=append
#SBATCH --gres=gpu:4

module purge
module load Miniconda3 CUDA OpenMPI

source activate py39
python3 -u prj001.py
```
- prj001.py (minimal project):
```
import sys
sys.path.insert(1,'../../../SUSAN')
import susan

mngr = susan.project.Manager('prj001',80)
mngr.initial_reference = 'prj001.refstxt'
mngr.initial_particles = 'prj001.ptclsraw'
mngr.tomogram_file     = 'tomos_b8.tomostxt'
mngr.list_gpus_ids     = [0,1,2,3]
mngr.aligner.ctf_correction  = 'cfsc'
mngr.aligner.allow_drift     = True
mngr.averager.ctf_correction = 'phase_flip' # or 'wiener'
mngr.cc_threshold   = 0.5
mngr.iteration_type = 3

mngr.mpi.arg = 2

mngr.aligner.bandpass.highpass = 0
mngr.aligner.bandpass.lowpass  = 15
mngr.aligner.bandpass.rolloff  = 10

mngr.aligner.set_angular_search(0,1,0,1)
mngr.aligner.refine.levels = 0
mngr.aligner.refine.factor = 1
mngr.aligner.set_offset_search(4,1)
_ = mngr.execute_iteration(1)
```
- And execute accordingly:
```
sbatch susan_job_prj001.sh
```


Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Unfortunately, I cant book more than 4 gpus total (we have 4-gpu nodes) and booking only two on reach node is not working for susan since it asks for gpu ids directly. I can of course get the ids with SLURM_JOB_GPUS but the ids assigned are different on two nodes. I think I'll stick to running on a single node - so no MPI necessary. 

A small question though, in your script you dont set mpi.cmd and it's default is "srun -n 2". Do you execute srun on assigned node inside sbatch submitted job? I expected you to use "mpirun -n 2" for example, not srun.

**Comment by rsanchezloayza** [comment]
Hi Grigory,
SUSAN was designed to run once instance per node, so, in your case, no MPI is necessary. I will consider to add the option to automatically detect the GPUs IDs, but that would be after I finish the manuscript for the preprint.
Initially I was using "mpirun" but I had some compatibility issues. It was easier to use "srun" on SLURM clusters, and as I didn't want to be fixed to one of those, I exposed that part as a property of the project. I am relatively new to SLURM clusters, and from what I have read, it is better to use "srun" than "mpirun" on those ([4-years-old stackoverflow question about it](https://stackoverflow.com/questions/51300165/any-use-case-for-mpirun-on-slurm-managed-cluster)).
The philosophy of SUSAN is to be as flexible, modular, and "hackable" as possible, and also to be easy to integrate to existing high level pipelines. So, any feedback is greatly appreciated.
Best regards,
Ricardo.

**Comment by rsanchezloayza** [comment]
Hi Grigory,
should I close this issue?
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
@rkms86 I have finally found the purpose of duplicate command:
```
# Duplicate reference to run a MRA project
ptcls = susan.data.Particles('prj_001.ptclsraw')
susan.data.Particles.MRA.duplicate(ptcls,0)
ptcls.save('prj_001_mra.ptclsraw')
```
If I dont do it, the classificatiion is not working because all my particles have ref_id =1. So I have a follow-up question: if I would have 3 references I need to run this command twice? Will this increase the filesize of ptclsraw?

**Comment by rsanchezloayza** [comment]
Hi Grigory,
Yes, you need to duplicate until you have the `n_refs` (property of `Particles`) you want. The size will increase as the matrices holding the 3D alignments (rotations/translation/score) need to keep track of each reference.
Sometimes, before duplicating the particles I clear the shifts:
```
ptcls.update_position()
```
and I could also disable the drift while aligning:
```
mngr.aligner.allow_drift = False
```
Or allow drift and then discarding the particles that drifted away.

**Comment by azazellochg** [comment]
Hi Ricardo, thanks! 

A few more questions: 
1) the input TS are expected to be aligned. Are there any plans to allow unaligned TS + import alignment from e.g. imod xf to reduce interpolation?
2) import particles from tbl essentially imports only the coordinates but no orientations. Is this intended because you are working with substacks and the transformations are not a compatible?

**Comment by rsanchezloayza** [comment]
Hi Grigory,
Good questions, so:
1. Theoretically, unaligned TS is supported, as the information of the XF could be added to the Tomogram class quite easily, but I haven't tested that functionality that well. The option to import the XF file is available on the Matlab package, but I haven't port it to Python. I understand about the interpolations, but unless your subtomograms' results are getting close to nyquist and there is no option to go to an unbinned level, I think it is not crucial (I got no gains using the unaligned TS on the early development stage). Also, it is easier to relate the particles location to an aligned stack (that can be quickly reconstructed) than the unaligned one. 
2. Substacks are compact representation of Subtomograms, so, the 3D alignments should be compatible, as long as they are in the same representation. Dynamo uses ZXZ while SUSAN uses ZYZ, which should be compatible with Relion. The transformation should be easy to do, but I haven't done it yet. I would need to prepare a Dynamo project to validate the math... and that can take some time... I will check how TeamTomo does the conversion and then implement it here.

Both functionalities are straightforward to implement, and are indeed planned to be added in the near future.

**Comment by azazellochg** [comment]
Hi @rkms86 , another question came up: if the particles are duplicated when doing classification, they are not allowed to ever jump between ref_ids (e.g. there's a param in Dynamo for that)? Otherwise you might have duplicated particles (within a class) which will affect FSC.

**Comment by rsanchezloayza** [comment]
Hi Grigory,
`susan.data.Particles.MRA.duplicate` allocates 3D alignment information to each particle, the particle is not duplicated (`n_ptcl` is the same, but `n_refs` increases). After the alignment, the `ref_idx` property is updated according to the highest CC. Then, the reconstruction process *inserts* the substack into the respective reconstruction/halfmap. In principle, you can change how `ref_idx` is updated by overloading the `susan.project.Manager.exec_particle_selection` method.
To actually duplicate a particle, like in a symmetry expansion process or to create more particles using a known geometry, you could use `susan.data.particles.Geom.expand_by_rot_shift` (to test the angles and shifts you can use `susan.data.particles.Geom.rot_shift`).
For example, to rotate the reconstruction and recenter (examples written from the top of my head, haven't tested the code):
```
euZYZ = (0,90,0)
shift = (0,0,10) # In angstroms
susan.data.particles.Geom.rot_shift(ptcls,eZYZdeg=euZYZ,t=shift)
```
To do C3 symmetry expansion:
```
euZYZ = np.zeros(3,3)
euZYZ[:,0] = (0,120,240)
shift = np.zeros(3,3)
ptcls_exp = susan.data.particles.Geom.expand_by_rot_shift(ptcls,eZYZdeg=euZYZ,t=shift)
```
I don't know if this solves the question (or if I sway too much from the original question?)
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Hi! thanks for a very detailed answer :) I'm not trying to do anything fancy, just working on integrating SUSAN into Scipion (https://github.com/scipion-em/scipion-em-susantomo) and making sure I can at least complete the tutorial.

**Comment by rsanchezloayza** [comment]
Hi!
that's great! one of the purposes of susan is for it to be integrated into other frameworks, and I am happy to hear that it is already being integrated into Scipion. Thanks a lot! And thank you for adding the reference, but I have a small note on that (the DOI). There are two references in the math involving susan, the one from the SCIA2019 conference and the one from EUSIPCO2019, The first one proves mathematical the equivalence of doing crosscorrelation between volumes and volumes/projections, the second evaluates the performance of the alignment of volumes using that crosscorrelation algorithm (won best student paper award on that conference). The one you cite is the SCIA one, but with the EUSIPCO DOI, At this point doesn't matter much, I guess.
I am working on a longer, more detailed, tutorial (including a small subset of the HIV dataset) which will be released together with the preprint. And if you have any other doubts, do not hesitate in message me, I will happily address them.
Best regards,
Ricardo.

**Comment by azazellochg** [comment]
A much simpler question then: during the MRA run the reconstructed averages and half-maps from the last iteration are identical to the ones I can generate with avgr.reconstruct (assuming I'm not changing the pixel size, ctf corr method or using less particles with mngr.cc_threshold)?

**Comment by rsanchezloayza** [comment]
Exactly, they would be the same.

**Comment by azazellochg** [comment]
Hi Ricardo,

I'm back to running susan again. A few questions have come up:

1) as I can see in the tutorial, the particles/averages are always black on white. The masks are normal: white=1, black=0. This is the convention required by susan? E.g. tilt series also should be black on white?

2) When calculating fsc I noticed it uses the first fourier pixel that is <0.143. If I convert the fsc array to angstroms and check fsc=0.143 I get a different value (between the fourier shells, but depend on pixel/box size). Is this the way FSC is calculated in dynamo as well?

3) in the tutorial I'm at the step:
```
p1 = mngr.get_ptcls(10)
_ = plt.hist(p1.ali_cc[0],200)
susan.data.Particles.MRA.duplicate(p1,0)
p1.ref_cix[:] = p1.ali_cc[0]<0.05
p1.save('prj_003.ptclsraw')
```
What does p1.ref_cix[:] = p1.ali_cc[0]<0.05 do? Select particles with CC<0.05 for both references? Aren't you refining the worst particles then?

Grigory.

**Comment by rsanchezloayza** [comment]
Hi Grigory,
1. The tilt series should match the contrast of the references/averages. SUSAN calculates the cross-correlation and discards any negative value, so the sign of what can be consider signal should match. I did all my tests on black contrast, but it should work on the other case. Also, the masks are multiplied to the reference as they are, so you can have *downweight* some specific part.
2. I tried to mimic `dynamo_fsc` behavior, and I know that I validated that on the MATLAB implementation, but haven't done it on the Python on. During the week I will check it. If you have your own FSC function, you can add something like this to the iteration loop:
```
for i in range(...):
    ...
    half1,half2 = mngr.get_names_halfmaps(i)
    new_lowpass = get_fsc_threshold(half1,half2)
```
3. So, in `susan.data.Particles.MRA.duplicate(p1,0)` we duplicated the previous 3D alignment information so we have two classes now, but all of them are assigned to the first reference/class (ref_cix = 0). With `p1.ref_cix[:] = p1.ali_cc[0]<0.05` I set to class index such as when I reconstruct `prj_003.ptclsraw` I will have one reference with the best particles and other one with the worst. Then I would run a MRA project to clean up some particles (keep the good class/reference). Let me know if I should explain this part better.

Best regards,
Ricardo.

**Comment by azazellochg** [comment]
Hi, 
1) got it, thanks!
2) [this](https://github.com/rkms86/SUSAN/blob/main/susan/utils/_functions.py#L146) is where the fpix is selected. E.g., at 10 fpx fsc is 0.25 and at 11 fpx fsc is 0.10. Susan will print 11px as a result (and convert to Angstroms). I thought it would be interpolated to a value between fpix where fsc is exactly 0.143
3) I think I got the idea. Will have to think how to implement this in my wrapper..

Thank you!
Grigory.

**Comment by rsanchezloayza** [comment]
Hi Grigory,
1. Cool.
2. Ah, that's what you meant . Ok, I didn't implement the interpolation as I was using that value to control the low pass values and with integer numbers was enough. I will consider adding it.
3. Well, selecting the classes can be difficult. Typically, I check the histogram of the CC of an alignment project and see if there are outliers or multiple modes and set the number of classes (and ref_cix) accordingly. It is not as straight forward as in SPA, specially on heterogeneous data. You can always randomize the value, though.
Best regards,
Ricardo.
